groups:
  Player: []
disabled_commands:
- bungee
- end
- greload
- ip
- perms
- server
- stop
stats: ''
permissions: {}
player_limit: 3500
ip_forward: true
timeout: 16000
log_commands: false
online_mode: false
connection_throttle: 4000
network_compression_threshold: 256
listeners:
- max_players: 3500
  host: 94.130.116.180:25565
  bind_local_address: false
  ping_passthrough: false
  tab_list: SERVER
  forced_hosts: {}
  tab_size: 60
  force_default_server: false
  motd: '   &c☆ &e&lSpark&r &2&lGames&r &c| &3&lServers Network&r &c| &5[&61.8-1.16.3&5] &c☆           &fBedWars&9 | &fSkyBlock&9 | &fFighting&9 | &fDestroyer&9 | &fCreative&9 | &fSurvival'
  query_enabled: true
  query_port: 25565
  priorities:
  - Lobby
servers:
 # ----------------------------------------------
  Lobby:
    address: 127.0.0.1:5439
    restricted: false
    motd: ''
 # ----------------------------------------------
  BedWars:
    address: 127.0.0.1:5441
    restricted: false
    motd: ''
  Creative:
    address: 127.0.0.1:5443
    restricted: false
    motd: ''
  Fighting:
    address: 127.0.0.1:5445
    restricted: false
    motd: ''
  SkyBlock:
    address: 127.0.0.1:5447
    restricted: false
    motd: ''
  Destroyer:
    address: 127.0.0.1:5449
    restricted: false
    motd: ''
  Survival:
    address: 127.0.0.1:5451
    restricted: false
    motd: ''
 # ----------------------------------------------