issues: "https://github.com/Dimatert9/BungeeCord/issues"
help: "http://www.rubukkit.org/threads/137038/"
config-version: 1
bot-filter-version: "3.0.4"
messages:
  prefix: "&c[&7Anti&6Bot&c]&r"
  checking: "%prefix% &eОжидайте завершения проверки..."
  checking-captcha: "%prefix% &aВведите в чат код с картинки"
  checking-captcha-wrong: "%prefix% &cВы ввели неверный код с картинки &6(&eосталось %s %s&6)"
  successfully: "%prefix% &aПроверка успешно пройдена."
  kick-many-checks: "%prefix% &cПревышен лимит подключений."
  kick-not-player: "%prefix% &cВы не прошли проверку."
  kick-country: "%prefix% &4Подключение временно ограничено. Повторите попытку через несколько секунд."
  kick-big-ping: "%prefix% &cНестабильное соединение. Повторите попытку через несколько секунд."
protection-threshold: 20
protection-time: 120000
show-online: true
time: 18000
time-out: 14000
geo-ip:
  mode: 1
  geoip-download-url: "http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  allowed-countries: 
  - "RU"
  - "UA"
  - "KZ"
  - "BY"
ping-check:
  mode: 1
  max-ping: 250
server-ping-check:
  mode: 1
  cache-time: 20
  kick-message:
  - "&cНедопустимая сессия. Попробуйте перезапустить игру."
protection:
  normal: 2
  on-attack: 1
sql:
  storage-type: "sqlite"
  purge-time: 14
  hostname: "127.0.0.1"
  port: 3306
  user: "root"
  password: "password"
  database: "database"